---

# vars file for redis

redis_yum_repo:
  Amazon: amzn2extra-epel
  CentOS: epel
  Fedora: epel

redis_conf_path:
  RedHat: '/etc'
  Debian: '/etc/redis'

redis_service:
  RedHat: redis
  Debian: redis-server
